"""Initial schema

Revision ID: 2c7539e3f87d
Revises: 
Create Date: 2026-08-03 13:46:17.510366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c7539e3f87d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch_staff',
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('branch_id', 'user_id')
    )
    op.create_index('ix_branch_staff_user_id', 'branch_staff', ['user_id'], unique=False)
    op.create_table('branches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('branch_name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_branches_business_id', 'branches', ['business_id'], unique=False)
    op.create_table('businesses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_businesses_owner_user_id', 'businesses', ['owner_user_id'], unique=False)
    op.create_table('customer_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_record_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.String(length=1000), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customer_notes_record_id', 'customer_notes', ['customer_record_id'], unique=False)
    op.create_table('customer_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_record_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('order_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index('ix_customer_orders_record_id', 'customer_orders', ['customer_record_id'], unique=False)
    op.create_table('customer_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('first_contact_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('total_spend', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('buyer_id', 'seller_id', name='uq_crm_buyer_seller')
    )
    op.create_index('ix_crm_buyer_id', 'customer_records', ['buyer_id'], unique=False)
    op.create_index('ix_crm_seller_id', 'customer_records', ['seller_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_ref', sa.Text(), nullable=True),
    sa.Column('invoice_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoices_user_id', 'invoices', ['user_id'], unique=False)
    op.create_table('kyc_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('s3_key', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("document_type IN ('government_id','business_registration')", name='ck_kyc_document_type'),
    sa.CheckConstraint("status IN ('pending','approved','rejected')", name='ck_kyc_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kyc_documents_user_id', 'kyc_documents', ['user_id'], unique=False)
    op.create_table('message_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_message_queue_recipient_id', 'message_queue', ['recipient_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('media_s3_key', sa.Text(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_created_at', 'messages', ['created_at'], unique=False)
    op.create_index('ix_messages_thread_id', 'messages', ['thread_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.Column('sms_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('whatsapp_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notif_pref_user_id', 'notification_preferences', ['user_id'], unique=False)
    op.create_table('order_facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('business_id', sa.UUID(), nullable=True),
    sa.Column('listing_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('order_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index('ix_order_facts_branch_id', 'order_facts', ['branch_id'], unique=False)
    op.create_index('ix_order_facts_buyer_id', 'order_facts', ['buyer_id'], unique=False)
    op.create_index('ix_order_facts_order_date', 'order_facts', ['order_date'], unique=False)
    op.create_index('ix_order_facts_seller_id', 'order_facts', ['seller_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('gateway', sa.String(length=20), nullable=False),
    sa.Column('gateway_ref', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('escrow_held_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_release_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("gateway IN ('paystack','flutterwave','mpesa','wallet')", name='ck_payments_gateway'),
    sa.CheckConstraint("status IN ('pending','processing','held_in_escrow','released','refunded','failed')", name='ck_payments_status'),
    sa.CheckConstraint('amount > 0', name='ck_payments_amount_positive'),
    sa.CheckConstraint('fee_amount >= 0', name='ck_payments_fee_amount_nonneg'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', name='uq_payments_order_id')
    )
    op.create_index('ix_payments_auto_release_at', 'payments', ['auto_release_at'], unique=False)
    op.create_index('ix_payments_buyer_id', 'payments', ['buyer_id'], unique=False)
    op.create_index('ix_payments_created_at', 'payments', ['created_at'], unique=False)
    op.create_index('ix_payments_order_id', 'payments', ['order_id'], unique=False)
    op.create_index('ix_payments_seller_id', 'payments', ['seller_id'], unique=False)
    op.create_index('ix_payments_status', 'payments', ['status'], unique=False)
    op.create_table('profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('profile_photo_url', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('trust_badge', sa.String(length=20), nullable=False),
    sa.Column('subscription_tier', sa.String(length=20), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("default_currency IN ('NGN','GHS','KES','ZAR','XOF')", name='ck_profiles_currency'),
    sa.CheckConstraint("subscription_tier IN ('starter','growth','pro','enterprise')", name='ck_profiles_tier'),
    sa.CheckConstraint("trust_badge IN ('none','bronze','silver','gold','diamond')", name='ck_profiles_trust_badge'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('ix_profiles_email', 'profiles', ['email'], unique=False)
    op.create_table('shipment_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shipment_id', sa.UUID(), nullable=False),
    sa.Column('carrier_status', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shipment_events_shipment_id', 'shipment_events', ['shipment_id'], unique=False)
    op.create_table('shipments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('carrier', sa.String(length=30), nullable=False),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('origin_address', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('destination_address', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('dimensions_cm', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estimated_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('proof_asset_url', sa.Text(), nullable=True),
    sa.Column('proof_status', sa.String(length=20), nullable=False),
    sa.Column('carrier_tracking_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("carrier IN ('gig','dhl','fedex','local_rider')", name='ck_shipment_carrier'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shipments_order_id', 'shipments', ['order_id'], unique=False)
    op.create_index('ix_shipments_tracking_number', 'shipments', ['tracking_number'], unique=False)
    op.create_table('stock_damages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('quantity_damaged', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity_damaged > 0', name='ck_damage_quantity_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('movement_type', sa.String(length=30), nullable=False),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('quantity_after', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("movement_type IN ('sale', 'transfer_out', 'transfer_in', 'damage', 'adjustment', 'initial')", name='ck_movement_type_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stock_movements_created_at', 'stock_movements', ['created_at'], unique=False)
    op.create_index('ix_stock_movements_sku_branch', 'stock_movements', ['sku', 'branch_id'], unique=False)
    op.create_table('stock_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=False),
    sa.Column('quantity_reserved', sa.Integer(), nullable=False),
    sa.Column('quantity_damaged', sa.Integer(), nullable=False),
    sa.Column('reorder_threshold', sa.Integer(), nullable=False),
    sa.Column('barcode_s3_key', sa.Text(), nullable=True),
    sa.Column('qr_code_s3_key', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity_damaged >= 0', name='ck_stock_damaged_non_neg'),
    sa.CheckConstraint('quantity_on_hand >= 0', name='ck_stock_on_hand_non_neg'),
    sa.CheckConstraint('quantity_reserved <= quantity_on_hand', name='ck_stock_reserved_lte_on_hand'),
    sa.CheckConstraint('quantity_reserved >= 0', name='ck_stock_reserved_non_neg'),
    sa.CheckConstraint('reorder_threshold >= 0', name='ck_stock_reorder_non_neg'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku', 'branch_id', name='uq_stock_sku_branch')
    )
    op.create_index('ix_stock_records_branch_id', 'stock_records', ['branch_id'], unique=False)
    op.create_index('ix_stock_records_sku', 'stock_records', ['sku'], unique=False)
    op.create_table('stock_transfers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('from_branch_id', sa.UUID(), nullable=False),
    sa.Column('to_branch_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('initiated_by', sa.UUID(), nullable=True),
    sa.Column('confirmed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'confirmed', 'cancelled')", name='ck_transfer_status_valid'),
    sa.CheckConstraint('quantity > 0', name='ck_transfer_quantity_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('participant_a', sa.UUID(), nullable=False),
    sa.Column('participant_b', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participant_a', 'participant_b', 'listing_id', name='uq_thread_participants')
    )
    op.create_index('ix_threads_participant_a', 'threads', ['participant_a'], unique=False)
    op.create_index('ix_threads_participant_b', 'threads', ['participant_b'], unique=False)
    op.create_table('wallets',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='NGN', nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('held_balance', sa.Numeric(precision=18, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('rewards_points', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('balance >= 0', name='ck_wallets_balance_nonneg'),
    sa.CheckConstraint('held_balance >= 0', name='ck_wallets_held_balance_nonneg'),
    sa.CheckConstraint('rewards_points >= 0', name='ck_wallets_rewards_points_nonneg'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('disputes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('raised_by', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='open', nullable=False),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('open','resolved_buyer','resolved_seller')", name='ck_disputes_status'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_disputes_created_at', 'disputes', ['created_at'], unique=False)
    op.create_index('ix_disputes_payment_id', 'disputes', ['payment_id'], unique=False)
    op.create_index('ix_disputes_raised_by', 'disputes', ['raised_by'], unique=False)
    op.create_index('ix_disputes_status', 'disputes', ['status'], unique=False)
    op.create_table('fraud_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('rejected', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 1', name='ck_fraud_scores_score_range'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fraud_scores_payment_id', 'fraud_scores', ['payment_id'], unique=False)
    op.create_index('ix_fraud_scores_rejected', 'fraud_scores', ['rejected'], unique=False)
    op.create_index('ix_fraud_scores_scored_at', 'fraud_scores', ['scored_at'], unique=False)
    op.create_table('wallet_transactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('wallet_user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False, comment='credit | debit | hold | release | cashback | rewards_credit | rewards_redemption | withdrawal'),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True, comment='payment_id, transfer_id, or other cross-service reference'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='completed', nullable=False, comment='completed | processing | failed'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_wallet_tx_amount_positive'),
    sa.CheckConstraint('balance_after >= 0', name='ck_wallet_tx_balance_after_nonneg'),
    sa.ForeignKeyConstraint(['wallet_user_id'], ['wallets.user_id'], name='fk_wallet_tx_wallet_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wallet_tx_created_at', 'wallet_transactions', ['created_at'], unique=False)
    op.create_index('ix_wallet_tx_reference_id', 'wallet_transactions', ['reference_id'], unique=False)
    op.create_index('ix_wallet_tx_wallet_user_id', 'wallet_transactions', ['wallet_user_id'], unique=False)
    op.drop_table('platform_config')
    op.drop_index(op.f('ix_saved_listings_user_id'), table_name='saved_listings')
    op.drop_table('saved_listings')
    op.drop_index(op.f('ix_audit_log_actor'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_cat'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_sub_pay_paid'), table_name='sub_payments')
    op.drop_index(op.f('ix_sub_pay_user'), table_name='sub_payments')
    op.drop_table('sub_payments')
    op.drop_table('password_change_otps')
    op.alter_column('audit_logs', 'id',
               existing_type=sa.TEXT(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.TEXT(),
               type_=postgresql.INET(),
               existing_nullable=True)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.alter_column('bookings', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('devices', 'id',
               existing_type=sa.TEXT(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('devices', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('devices', 'fingerprint',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('devices', 'ip_address',
               existing_type=sa.TEXT(),
               type_=postgresql.INET(),
               existing_nullable=True)
    op.drop_constraint(op.f('devices_user_id_fingerprint_key'), 'devices', type_='unique')
    op.create_unique_constraint('uq_devices_user_fingerprint', 'devices', ['user_id', 'fingerprint'])
    op.alter_column('job_applications', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.drop_index(op.f('ix_job_apps_applicant_id'), table_name='job_applications')
    op.drop_index(op.f('ix_job_apps_listing_id'), table_name='job_applications')
    op.create_index('ix_job_applications_applicant_id', 'job_applications', ['applicant_id'], unique=False)
    op.create_index('ix_job_applications_listing_id', 'job_applications', ['listing_id'], unique=False)
    op.alter_column('job_details', 'job_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('job_details', 'salary_currency',
               existing_type=sa.TEXT(),
               type_=sa.String(length=3),
               existing_nullable=True)
    op.alter_column('listing_media', 'media_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('listing_media', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('listing_specs', 'spec_key',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('listing_variants', 'sku',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('listings', 'listing_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('listings', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('listings', 'currency',
               existing_type=sa.TEXT(),
               type_=sa.String(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'NGN'::text"))
    op.alter_column('listings', 'country',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2),
               existing_nullable=True)
    op.alter_column('listings', 'state',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('listings', 'city',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('listings', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('listings', 'subcategory',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('listings', 'condition',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('listings', 'brand',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('listings', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::text"))
    op.alter_column('listings', 'whatsapp_number',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('listings', 'contact_phone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('login_history', 'id',
               existing_type=sa.TEXT(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('login_history', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('login_history', 'device_fingerprint',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('login_history', 'ip_address',
               existing_type=sa.TEXT(),
               type_=postgresql.INET(),
               existing_nullable=True)
    op.add_column('notifications', sa.Column('recipient_user_id', sa.UUID(), nullable=False))
    op.add_column('notifications', sa.Column('channel', sa.String(length=20), nullable=False))
    op.add_column('notifications', sa.Column('notification_type', sa.String(length=100), nullable=False))
    op.add_column('notifications', sa.Column('content', sa.Text(), nullable=False))
    op.add_column('notifications', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('notifications', sa.Column('attempts', sa.Integer(), nullable=False))
    op.add_column('notifications', sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('notifications', sa.Column('failure_reason', sa.Text(), nullable=True))
    op.alter_column('notifications', 'id',
               existing_type=sa.TEXT(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_index(op.f('ix_notifications_user'), table_name='notifications')
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('ix_notifications_user_id', 'notifications', ['recipient_user_id'], unique=False)
    op.drop_column('notifications', 'type')
    op.drop_column('notifications', 'title')
    op.drop_column('notifications', 'user_id')
    op.drop_column('notifications', 'is_read')
    op.drop_column('notifications', 'message')
    op.alter_column('otps', 'id',
               existing_type=sa.TEXT(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('otps', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('otps', 'purpose',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('otps', 'code_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('property_details', 'property_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('property_details', 'furnishing_status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('refresh_tokens', 'id',
               existing_type=sa.TEXT(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'token_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'device_fingerprint',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_index('ix_refresh_tokens_token_hash', 'refresh_tokens', ['token_hash'], unique=False)
    op.alter_column('review_eligibility', 'granted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('review_media', 'media_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('reviews', 'comment',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2000),
               existing_nullable=True)
    op.alter_column('reviews', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'published'::text"))
    op.alter_column('reviews', 'seller_response',
               existing_type=sa.TEXT(),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.drop_constraint(op.f('reviews_listing_id_reviewer_id_key'), 'reviews', type_='unique')
    op.create_unique_constraint('uq_reviews_listing_reviewer', 'reviews', ['listing_id', 'reviewer_id'])
    op.alter_column('stores', 'store_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('stores', 'theme',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('stores', 'custom_domain',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('stores', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('subscriptions', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.alter_column('subscriptions', 'id',
               existing_type=sa.TEXT(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('subscriptions', 'tier',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'starter'::text"))
    op.alter_column('subscriptions', 'pending_downgrade_tier',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('subscriptions', 'current_period_start',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_subscriptions_user'), table_name='subscriptions')
    op.create_index('ix_subscriptions_user_id', 'subscriptions', ['user_id'], unique=False)
    op.alter_column('totp_secrets', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('user_roles', 'id',
               existing_type=sa.TEXT(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('user_roles', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('user_roles', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('user_roles', 'scope_id',
               existing_type=sa.TEXT(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('user_roles', 'granted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('uq_user_roles_user_role'), table_name='user_roles')
    op.create_unique_constraint('uq_user_roles_user_role', 'user_roles', ['user_id', 'role'])
    op.alter_column('users', 'id',
               existing_type=sa.TEXT(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('users', 'phone_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               nullable=False)
    op.alter_column('users', 'country_code',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2),
               nullable=False,
               existing_server_default=sa.text("'NG'::text"))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'is_locked',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'failed_attempts',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_users_phone', 'users', ['phone'], unique=False)
    op.create_unique_constraint(None, 'users', ['phone'])
    op.drop_column('users', 'is_phone_verified')
    op.alter_column('vehicle_details', 'make',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('vehicle_details', 'model',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('vehicle_details', 'fuel_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('vehicle_details', 'transmission',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('vehicle_details', 'colour',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('vehicle_details', 'vin',
               existing_type=sa.TEXT(),
               type_=sa.String(length=17),
               existing_nullable=True)
    op.alter_column('vehicle_details', 'vin_history_status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicle_details', 'vin_history_status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.alter_column('vehicle_details', 'vin',
               existing_type=sa.String(length=17),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('vehicle_details', 'colour',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('vehicle_details', 'transmission',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('vehicle_details', 'fuel_type',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('vehicle_details', 'model',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('vehicle_details', 'make',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('users', sa.Column('is_phone_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index('ix_users_phone', table_name='users')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'failed_attempts',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'is_locked',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'country_code',
               existing_type=sa.String(length=2),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'NG'::text"))
    op.alter_column('users', 'full_name',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'phone_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'phone',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint('uq_user_roles_user_role', 'user_roles', type_='unique')
    op.create_index(op.f('uq_user_roles_user_role'), 'user_roles', ['user_id', 'role'], unique=True)
    op.alter_column('user_roles', 'granted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_roles', 'scope_id',
               existing_type=sa.UUID(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user_roles', 'role',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('user_roles', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('user_roles', 'id',
               existing_type=sa.UUID(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('totp_secrets', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index('ix_subscriptions_user_id', table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_user'), 'subscriptions', ['user_id'], unique=False)
    op.alter_column('subscriptions', 'current_period_start',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('subscriptions', 'pending_downgrade_tier',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('subscriptions', 'tier',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'starter'::text"))
    op.alter_column('subscriptions', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('subscriptions', 'id',
               existing_type=sa.UUID(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('subscriptions', 'retry_count')
    op.alter_column('stores', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('stores', 'custom_domain',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('stores', 'theme',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('stores', 'store_name',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint('uq_reviews_listing_reviewer', 'reviews', type_='unique')
    op.create_unique_constraint(op.f('reviews_listing_id_reviewer_id_key'), 'reviews', ['listing_id', 'reviewer_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('reviews', 'seller_response',
               existing_type=sa.String(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('reviews', 'status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'published'::text"))
    op.alter_column('reviews', 'comment',
               existing_type=sa.String(length=2000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('review_media', 'media_type',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('review_eligibility', 'granted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_refresh_tokens_token_hash', table_name='refresh_tokens')
    op.alter_column('refresh_tokens', 'device_fingerprint',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('refresh_tokens', 'token_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'id',
               existing_type=sa.UUID(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('property_details', 'furnishing_status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('property_details', 'property_type',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('otps', 'code_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('otps', 'purpose',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('otps', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('otps', 'id',
               existing_type=sa.UUID(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('notifications', sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('notifications', sa.Column('type', sa.TEXT(), server_default=sa.text("'system'::text"), autoincrement=False, nullable=False))
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.create_index(op.f('ix_notifications_user'), 'notifications', ['user_id'], unique=False)
    op.alter_column('notifications', 'id',
               existing_type=sa.UUID(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('notifications', 'failure_reason')
    op.drop_column('notifications', 'sent_at')
    op.drop_column('notifications', 'attempts')
    op.drop_column('notifications', 'status')
    op.drop_column('notifications', 'content')
    op.drop_column('notifications', 'notification_type')
    op.drop_column('notifications', 'channel')
    op.drop_column('notifications', 'recipient_user_id')
    op.alter_column('login_history', 'ip_address',
               existing_type=postgresql.INET(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('login_history', 'device_fingerprint',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('login_history', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('login_history', 'id',
               existing_type=sa.UUID(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('listings', 'contact_phone',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('listings', 'whatsapp_number',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('listings', 'status',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'::text"))
    op.alter_column('listings', 'brand',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('listings', 'condition',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('listings', 'subcategory',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('listings', 'category',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('listings', 'city',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('listings', 'state',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('listings', 'country',
               existing_type=sa.String(length=2),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('listings', 'currency',
               existing_type=sa.String(length=3),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'NGN'::text"))
    op.alter_column('listings', 'title',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('listings', 'listing_type',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('listing_variants', 'sku',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('listing_specs', 'spec_key',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('listing_media', 'uploaded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('listing_media', 'media_type',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('job_details', 'salary_currency',
               existing_type=sa.String(length=3),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('job_details', 'job_type',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index('ix_job_applications_listing_id', table_name='job_applications')
    op.drop_index('ix_job_applications_applicant_id', table_name='job_applications')
    op.create_index(op.f('ix_job_apps_listing_id'), 'job_applications', ['listing_id'], unique=False)
    op.create_index(op.f('ix_job_apps_applicant_id'), 'job_applications', ['applicant_id'], unique=False)
    op.alter_column('job_applications', 'status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.drop_constraint('uq_devices_user_fingerprint', 'devices', type_='unique')
    op.create_unique_constraint(op.f('devices_user_id_fingerprint_key'), 'devices', ['user_id', 'fingerprint'], postgresql_nulls_not_distinct=False)
    op.alter_column('devices', 'ip_address',
               existing_type=postgresql.INET(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('devices', 'fingerprint',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('devices', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('devices', 'id',
               existing_type=sa.UUID(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('bookings', 'status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::text"))
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.alter_column('audit_logs', 'ip_address',
               existing_type=postgresql.INET(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'id',
               existing_type=sa.UUID(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_table('password_change_otps',
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('otp', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('new_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('password_change_otps_pkey'))
    )
    op.create_table('sub_payments',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('plan', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('reference', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('amount_ngn', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'success'::text"), autoincrement=False, nullable=False),
    sa.Column('paid_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('sub_payments_pkey'))
    )
    op.create_index(op.f('ix_sub_pay_user'), 'sub_payments', ['user_id'], unique=False)
    op.create_index(op.f('ix_sub_pay_paid'), 'sub_payments', ['paid_at'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('actor_email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('actor_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.TEXT(), server_default=sa.text("'system'::text"), autoincrement=False, nullable=False),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('resource', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'success'::text"), autoincrement=False, nullable=False),
    sa.Column('detail', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_log_pkey'))
    )
    op.create_index(op.f('ix_audit_log_created'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_cat'), 'audit_log', ['category'], unique=False)
    op.create_index(op.f('ix_audit_log_actor'), 'audit_log', ['actor_id'], unique=False)
    op.create_table('saved_listings',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('listing_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('saved_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('saved_listings_pkey')),
    sa.UniqueConstraint('user_id', 'listing_id', name=op.f('saved_listings_user_id_listing_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_saved_listings_user_id'), 'saved_listings', ['user_id'], unique=False)
    op.create_table('platform_config',
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('platform_config_pkey'))
    )
    op.drop_index('ix_wallet_tx_wallet_user_id', table_name='wallet_transactions')
    op.drop_index('ix_wallet_tx_reference_id', table_name='wallet_transactions')
    op.drop_index('ix_wallet_tx_created_at', table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index('ix_fraud_scores_scored_at', table_name='fraud_scores')
    op.drop_index('ix_fraud_scores_rejected', table_name='fraud_scores')
    op.drop_index('ix_fraud_scores_payment_id', table_name='fraud_scores')
    op.drop_table('fraud_scores')
    op.drop_index('ix_disputes_status', table_name='disputes')
    op.drop_index('ix_disputes_raised_by', table_name='disputes')
    op.drop_index('ix_disputes_payment_id', table_name='disputes')
    op.drop_index('ix_disputes_created_at', table_name='disputes')
    op.drop_table('disputes')
    op.drop_table('wallets')
    op.drop_index('ix_threads_participant_b', table_name='threads')
    op.drop_index('ix_threads_participant_a', table_name='threads')
    op.drop_table('threads')
    op.drop_table('stock_transfers')
    op.drop_index('ix_stock_records_sku', table_name='stock_records')
    op.drop_index('ix_stock_records_branch_id', table_name='stock_records')
    op.drop_table('stock_records')
    op.drop_index('ix_stock_movements_sku_branch', table_name='stock_movements')
    op.drop_index('ix_stock_movements_created_at', table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_table('stock_damages')
    op.drop_index('ix_shipments_tracking_number', table_name='shipments')
    op.drop_index('ix_shipments_order_id', table_name='shipments')
    op.drop_table('shipments')
    op.drop_index('ix_shipment_events_shipment_id', table_name='shipment_events')
    op.drop_table('shipment_events')
    op.drop_index('ix_profiles_email', table_name='profiles')
    op.drop_table('profiles')
    op.drop_index('ix_payments_status', table_name='payments')
    op.drop_index('ix_payments_seller_id', table_name='payments')
    op.drop_index('ix_payments_order_id', table_name='payments')
    op.drop_index('ix_payments_created_at', table_name='payments')
    op.drop_index('ix_payments_buyer_id', table_name='payments')
    op.drop_index('ix_payments_auto_release_at', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_order_facts_seller_id', table_name='order_facts')
    op.drop_index('ix_order_facts_order_date', table_name='order_facts')
    op.drop_index('ix_order_facts_buyer_id', table_name='order_facts')
    op.drop_index('ix_order_facts_branch_id', table_name='order_facts')
    op.drop_table('order_facts')
    op.drop_index('ix_notif_pref_user_id', table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index('ix_messages_thread_id', table_name='messages')
    op.drop_index('ix_messages_created_at', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_message_queue_recipient_id', table_name='message_queue')
    op.drop_table('message_queue')
    op.drop_index('ix_kyc_documents_user_id', table_name='kyc_documents')
    op.drop_table('kyc_documents')
    op.drop_index('ix_invoices_user_id', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('ix_crm_seller_id', table_name='customer_records')
    op.drop_index('ix_crm_buyer_id', table_name='customer_records')
    op.drop_table('customer_records')
    op.drop_index('ix_customer_orders_record_id', table_name='customer_orders')
    op.drop_table('customer_orders')
    op.drop_index('ix_customer_notes_record_id', table_name='customer_notes')
    op.drop_table('customer_notes')
    op.drop_index('ix_businesses_owner_user_id', table_name='businesses')
    op.drop_table('businesses')
    op.drop_index('ix_branches_business_id', table_name='branches')
    op.drop_table('branches')
    op.drop_index('ix_branch_staff_user_id', table_name='branch_staff')
    op.drop_table('branch_staff')
    # ### end Alembic commands ###
